# Generated by Django 4.0.10 on 2023-02-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfacewaterstation',
            name='utm_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surfacewaterstation',
            name='utm_y',
            field=models.FloatField(null=True),
        ),
    ]
