# Generated by Django 4.0.10 on 2023-02-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_alter_surfacewaterstation_utm_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfacewaterstation',
            name='div',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surfacewaterstation',
            name='por_end',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surfacewaterstation',
            name='por_start',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surfacewaterstation',
            name='usgs_station_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surfacewaterstation',
            name='wd',
            field=models.BigIntegerField(null=True),
        ),
    ]
